fix yaml.load error
fix yaml.load() errors
TypeError: load() missing 1 required positional argument: 'Loader'
HINT: you should use yaml.safe_load() instead of yaml.load() to read yaml files.
.
in pyyaml 3+: yaml.load(file) takes one argument
in pyyaml 5+: yaml.load(file, loader=LoaderClass) requires an extra argument to specify a loader.
the yaml library could save and load raw python object out-of-the-box, which is insecure, so it stopped supporting that out-of-the-box.
.
to read yaml files, you should use yaml.safe_load() instead.